### ISSUE TITLE
Error: Message malformed: required key not provided @ data['action']

### ISSUE THREAD

**Issue by martinorob** [thiagobruch/amazon_shopping_list_scrape#12]
I have pasted the code but I can't save because I receive the error in the title
```

description: ""
mode: single
trigger:
  - platform: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: true
    webhook_id: "-BLevbyo7s4SKkJpeaWRwMZJf"
condition: []
action:
  - action: todo.get_items
    data:
      status:
        - needs_action
        - completed
    response_variable: todo
    target:
      entity_id: todo.shopping_list
  - if:
      - condition: template
        value_template: |-
          {{trigger.json.name not in todo['todo.shopping_list']['items'] |
                    map(attribute='summary') | list}}
    then:
      - data_template:
          item: "{{ trigger.json.name }}"
        target:
          entity_id: todo.shopping_list
        action: todo.add_item
mode: parallel
max: 100

```

any suggestion?
